cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'fish'
brew 'java'
brew 'git'
brew 'gradle'
brew 'wget'
brew 'apktool'
brew 'git-delta'
brew 'youtube-dl'
brew 'ripgrep'
brew 'borgbackup'
brew 'atuin'

cask '1password'
cask 'google-chrome'
cask 'firefox'
cask 'jetbrains-toolbox'
cask 'android-file-transfer'
cask 'sublime-text'
cask 'appcleaner'
cask 'dropbox'
cask 'raycast'
cask 'spotify'
cask 'texifier'
